### ISSUE TITLE
Not possible to update application

### ISSUE THREAD

**Issue by akolpakov** [MongoApp/MongoApp#2]
When I'm trying to update, error comes:

Update Error!
The update is improperly signed.

**Comment by TofPlay** [comment]
Same thing for me (see screenhots)
![screen shot 2015-02-13 at 20 53 02](https://cloud.githubusercontent.com/assets/1082222/6194241/c5f6a140-b3c2-11e4-803b-15199c5aa617.png)
I download the version from the url and reinstall it that doesn't changed anything
![screen shot 2015-02-13 at 20 57 32](https://cloud.githubusercontent.com/assets/1082222/6194264/fbee70de-b3c2-11e4-9e43-ebca5c2135bc.png)

**Comment by wavded** [comment]
Get the same error.

**Comment by pkozlov** [comment]
Fixed in v3.0.1.4
If you see "The update is improperly signed", please download version from http://mongoapp.com/ or https://github.com/MongoApp/MongoApp/releases and reinstall it.
