### ISSUE TITLE
I'm looking for a NodeJs.app

### ISSUE THREAD

**Issue by TofPlay** [MongoApp/MongoApp#3]
Hi,
Is really great idea to create a Mac application like Mongo.app for MongoDB. :+1: :smile: 
Do you know if a same type of application exist for Node.js:question: 
Regards
Tof

**Comment by wavded** [comment]
@TofPlay why not just download the Mac build and use that installer for Node? https://nodejs.org/download/

**Comment by pkozlov** [comment]
Agree with @wavded
But may be it is great idea to create status bar application for running Express servers. I will think about it.
